/**
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DatasetConnector model module.
 * @module model/DatasetConnector
 * @version 0.0.1-SNAPSHOT
 */
class DatasetConnector {
    /**
     * Constructs a new <code>DatasetConnector</code>.
     * a Connector setup
     * @alias module:model/DatasetConnector
     * @param id {String} the Connector id
     */
    constructor(id) { 
        
        DatasetConnector.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>DatasetConnector</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DatasetConnector} obj Optional instance to populate.
     * @return {module:model/DatasetConnector} The populated <code>DatasetConnector</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DatasetConnector();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('parametersValues')) {
                obj['parametersValues'] = ApiClient.convertToType(data['parametersValues'], {'String': Object});
            }
        }
        return obj;
    }


}

/**
 * the Connector id
 * @member {String} id
 */
DatasetConnector.prototype['id'] = undefined;

/**
 * @member {Object.<String, Object>} parametersValues
 */
DatasetConnector.prototype['parametersValues'] = undefined;






export default DatasetConnector;

