/**
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 1.0.9-SNAPSHOT
 * Contact: platform@cosmotech.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrganizationService from './OrganizationService';

/**
 * The OrganizationServices model module.
 * @module model/OrganizationServices
 * @version 1.0.9-SNAPSHOT
 */
class OrganizationServices {
    /**
     * Constructs a new <code>OrganizationServices</code>.
     * the cloud service resources of the Organization
     * @alias module:model/OrganizationServices
     */
    constructor() { 
        
        OrganizationServices.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrganizationServices</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrganizationServices} obj Optional instance to populate.
     * @return {module:model/OrganizationServices} The populated <code>OrganizationServices</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrganizationServices();

            if (data.hasOwnProperty('tenantCredentials')) {
                obj['tenantCredentials'] = ApiClient.convertToType(data['tenantCredentials'], {'String': Object});
            }
            if (data.hasOwnProperty('storage')) {
                obj['storage'] = OrganizationService.constructFromObject(data['storage']);
            }
            if (data.hasOwnProperty('solutionsContainerRegistry')) {
                obj['solutionsContainerRegistry'] = OrganizationService.constructFromObject(data['solutionsContainerRegistry']);
            }
        }
        return obj;
    }


}

/**
 * a freeform credentials object for the Organization tenant. Structure depends on cloud provider
 * @member {Object.<String, Object>} tenantCredentials
 */
OrganizationServices.prototype['tenantCredentials'] = undefined;

/**
 * @member {module:model/OrganizationService} storage
 */
OrganizationServices.prototype['storage'] = undefined;

/**
 * @member {module:model/OrganizationService} solutionsContainerRegistry
 */
OrganizationServices.prototype['solutionsContainerRegistry'] = undefined;






export default OrganizationServices;

