/**
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PlatformService model module.
 * @module model/PlatformService
 * @version 0.0.1-SNAPSHOT
 */
class PlatformService {
    /**
     * Constructs a new <code>PlatformService</code>.
     * a Cloud Service resource
     * @alias module:model/PlatformService
     */
    constructor() { 
        
        PlatformService.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlatformService</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PlatformService} obj Optional instance to populate.
     * @return {module:model/PlatformService} The populated <code>PlatformService</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlatformService();

            if (data.hasOwnProperty('cloudService')) {
                obj['cloudService'] = ApiClient.convertToType(data['cloudService'], 'String');
            }
            if (data.hasOwnProperty('baseUri')) {
                obj['baseUri'] = ApiClient.convertToType(data['baseUri'], 'String');
            }
            if (data.hasOwnProperty('resourceUri')) {
                obj['resourceUri'] = ApiClient.convertToType(data['resourceUri'], 'String');
            }
            if (data.hasOwnProperty('credentials')) {
                obj['credentials'] = ApiClient.convertToType(data['credentials'], {'String': Object});
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], {'String': Object});
            }
        }
        return obj;
    }


}

/**
 * the cloud service name
 * @member {String} cloudService
 */
PlatformService.prototype['cloudService'] = undefined;

/**
 * the platform base uri for this service
 * @member {String} baseUri
 */
PlatformService.prototype['baseUri'] = undefined;

/**
 * the workspace specific uri for this service resource
 * @member {String} resourceUri
 */
PlatformService.prototype['resourceUri'] = undefined;

/**
 * a freeform credentials object. Structure depends on service
 * @member {Object.<String, Object>} credentials
 */
PlatformService.prototype['credentials'] = undefined;

/**
 * the service specific options
 * @member {Object.<String, Object>} options
 */
PlatformService.prototype['options'] = undefined;






export default PlatformService;

