/**
 * Cosmo Tech Platform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 4.0.3-SNAPSHOT
 * Contact: platform@cosmotech.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RunLogsEntry from './RunLogsEntry';

/**
 * The RunLogs model module.
 * @module model/RunLogs
 * @version 4.0.3-SNAPSHOT
 */
class RunLogs {
    /**
     * Constructs a new <code>RunLogs</code>.
     * the output logs of a run
     * @alias module:model/RunLogs
     * @param runId {String} the Run Id
     * @param logs {Array.<module:model/RunLogsEntry>} run log entries in chronological order
     */
    constructor(runId, logs) { 
        
        RunLogs.initialize(this, runId, logs);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, runId, logs) { 
        obj['runId'] = runId;
        obj['logs'] = logs;
    }

    /**
     * Constructs a <code>RunLogs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RunLogs} obj Optional instance to populate.
     * @return {module:model/RunLogs} The populated <code>RunLogs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RunLogs();

            if (data.hasOwnProperty('runId')) {
                obj['runId'] = ApiClient.convertToType(data['runId'], 'String');
            }
            if (data.hasOwnProperty('logs')) {
                obj['logs'] = ApiClient.convertToType(data['logs'], [RunLogsEntry]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RunLogs</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RunLogs</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RunLogs.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['runId'] && !(typeof data['runId'] === 'string' || data['runId'] instanceof String)) {
            throw new Error("Expected the field `runId` to be a primitive type in the JSON string but got " + data['runId']);
        }
        if (data['logs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['logs'])) {
                throw new Error("Expected the field `logs` to be an array in the JSON data but got " + data['logs']);
            }
            // validate the optional field `logs` (array)
            for (const item of data['logs']) {
                RunLogsEntry.validateJSON(item);
            };
        }

        return true;
    }


}

RunLogs.RequiredProperties = ["runId", "logs"];

/**
 * the Run Id
 * @member {String} runId
 */
RunLogs.prototype['runId'] = undefined;

/**
 * run log entries in chronological order
 * @member {Array.<module:model/RunLogsEntry>} logs
 */
RunLogs.prototype['logs'] = undefined;






export default RunLogs;

