/**
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScenarioRunAnalysisAllOf model module.
 * @module model/ScenarioRunAnalysisAllOf
 * @version 0.0.1-SNAPSHOT
 */
class ScenarioRunAnalysisAllOf {
    /**
     * Constructs a new <code>ScenarioRunAnalysisAllOf</code>.
     * a previously ran or running Scenario Analysis with run information
     * @alias module:model/ScenarioRunAnalysisAllOf
     */
    constructor() { 
        
        ScenarioRunAnalysisAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScenarioRunAnalysisAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScenarioRunAnalysisAllOf} obj Optional instance to populate.
     * @return {module:model/ScenarioRunAnalysisAllOf} The populated <code>ScenarioRunAnalysisAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScenarioRunAnalysisAllOf();

            if (data.hasOwnProperty('simulationId')) {
                obj['simulationId'] = ApiClient.convertToType(data['simulationId'], 'String');
            }
            if (data.hasOwnProperty('simulationState')) {
                obj['simulationState'] = ApiClient.convertToType(data['simulationState'], 'String');
            }
        }
        return obj;
    }


}

/**
 * the Simulation Run Id
 * @member {String} simulationId
 */
ScenarioRunAnalysisAllOf.prototype['simulationId'] = undefined;

/**
 * the Simulation Run State
 * @member {String} simulationState
 */
ScenarioRunAnalysisAllOf.prototype['simulationState'] = undefined;






export default ScenarioRunAnalysisAllOf;

