/**
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScenarioAnalysis from './ScenarioAnalysis';
import ScenarioAnalysisParameterValue from './ScenarioAnalysisParameterValue';
import ScenarioRunningAnalysisAllOf from './ScenarioRunningAnalysisAllOf';

/**
 * The ScenarioRunningAnalysis model module.
 * @module model/ScenarioRunningAnalysis
 * @version 0.0.1-SNAPSHOT
 */
class ScenarioRunningAnalysis {
    /**
     * Constructs a new <code>ScenarioRunningAnalysis</code>.
     * @alias module:model/ScenarioRunningAnalysis
     * @implements module:model/ScenarioAnalysis
     * @implements module:model/ScenarioRunningAnalysisAllOf
     */
    constructor() { 
        ScenarioAnalysis.initialize(this);ScenarioRunningAnalysisAllOf.initialize(this);
        ScenarioRunningAnalysis.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScenarioRunningAnalysis</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScenarioRunningAnalysis} obj Optional instance to populate.
     * @return {module:model/ScenarioRunningAnalysis} The populated <code>ScenarioRunningAnalysis</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScenarioRunningAnalysis();
            ScenarioAnalysis.constructFromObject(data, obj);
            ScenarioRunningAnalysisAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('analysisId')) {
                obj['analysisId'] = ApiClient.convertToType(data['analysisId'], 'String');
            }
            if (data.hasOwnProperty('datasetList')) {
                obj['datasetList'] = ApiClient.convertToType(data['datasetList'], ['String']);
            }
            if (data.hasOwnProperty('parametersValues')) {
                obj['parametersValues'] = ApiClient.convertToType(data['parametersValues'], [ScenarioAnalysisParameterValue]);
            }
            if (data.hasOwnProperty('sendInputToDataWarehouse')) {
                obj['sendInputToDataWarehouse'] = ApiClient.convertToType(data['sendInputToDataWarehouse'], 'Boolean');
            }
            if (data.hasOwnProperty('simulationId')) {
                obj['simulationId'] = ApiClient.convertToType(data['simulationId'], 'String');
            }
            if (data.hasOwnProperty('jobId')) {
                obj['jobId'] = ApiClient.convertToType(data['jobId'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
        }
        return obj;
    }


}

/**
 * the Simulator Analysis Id associated with this Scenario
 * @member {String} analysisId
 */
ScenarioRunningAnalysis.prototype['analysisId'] = undefined;

/**
 * the list of Dataset Id associated to this Scenario Analysis
 * @member {Array.<String>} datasetList
 */
ScenarioRunningAnalysis.prototype['datasetList'] = undefined;

/**
 * the list of Simulator Analysis parameters values
 * @member {Array.<module:model/ScenarioAnalysisParameterValue>} parametersValues
 */
ScenarioRunningAnalysis.prototype['parametersValues'] = undefined;

/**
 * whether or not the Dataset values and the input parameters values are send to the DataWarehouse prior to Simulation Run
 * @member {Boolean} sendInputToDataWarehouse
 */
ScenarioRunningAnalysis.prototype['sendInputToDataWarehouse'] = undefined;

/**
 * the Simulation Run Id
 * @member {String} simulationId
 */
ScenarioRunningAnalysis.prototype['simulationId'] = undefined;

/**
 * the compute cluster job Id
 * @member {String} jobId
 */
ScenarioRunningAnalysis.prototype['jobId'] = undefined;

/**
 * the job state
 * @member {String} state
 */
ScenarioRunningAnalysis.prototype['state'] = undefined;


// Implement ScenarioAnalysis interface:
/**
 * the Simulator Analysis Id associated with this Scenario
 * @member {String} analysisId
 */
ScenarioAnalysis.prototype['analysisId'] = undefined;
/**
 * the list of Dataset Id associated to this Scenario Analysis
 * @member {Array.<String>} datasetList
 */
ScenarioAnalysis.prototype['datasetList'] = undefined;
/**
 * the list of Simulator Analysis parameters values
 * @member {Array.<module:model/ScenarioAnalysisParameterValue>} parametersValues
 */
ScenarioAnalysis.prototype['parametersValues'] = undefined;
/**
 * whether or not the Dataset values and the input parameters values are send to the DataWarehouse prior to Simulation Run
 * @member {Boolean} sendInputToDataWarehouse
 */
ScenarioAnalysis.prototype['sendInputToDataWarehouse'] = undefined;
// Implement ScenarioRunningAnalysisAllOf interface:
/**
 * the Simulation Run Id
 * @member {String} simulationId
 */
ScenarioRunningAnalysisAllOf.prototype['simulationId'] = undefined;
/**
 * the compute cluster job Id
 * @member {String} jobId
 */
ScenarioRunningAnalysisAllOf.prototype['jobId'] = undefined;
/**
 * the job state
 * @member {String} state
 */
ScenarioRunningAnalysisAllOf.prototype['state'] = undefined;




export default ScenarioRunningAnalysis;

