/**
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScenarioRunStart model module.
 * @module model/ScenarioRunStart
 * @version 0.0.1-SNAPSHOT
 */
class ScenarioRunStart {
    /**
     * Constructs a new <code>ScenarioRunStart</code>.
     * the parameters to run a Scenario
     * @alias module:model/ScenarioRunStart
     */
    constructor() { 
        
        ScenarioRunStart.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScenarioRunStart</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScenarioRunStart} obj Optional instance to populate.
     * @return {module:model/ScenarioRunStart} The populated <code>ScenarioRunStart</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScenarioRunStart();

            if (data.hasOwnProperty('workspaceId')) {
                obj['workspaceId'] = ApiClient.convertToType(data['workspaceId'], 'String');
            }
            if (data.hasOwnProperty('scenarioId')) {
                obj['scenarioId'] = ApiClient.convertToType(data['scenarioId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * the Workspace Id
 * @member {String} workspaceId
 */
ScenarioRunStart.prototype['workspaceId'] = undefined;

/**
 * the Scenario Id
 * @member {String} scenarioId
 */
ScenarioRunStart.prototype['scenarioId'] = undefined;






export default ScenarioRunStart;

