/**
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ScenarioRunContainerLog model module.
 * @module model/ScenarioRunContainerLog
 * @version 0.0.1-SNAPSHOT
 */
class ScenarioRunContainerLog {
    /**
     * Constructs a new <code>ScenarioRunContainerLog</code>.
     * a container log line
     * @alias module:model/ScenarioRunContainerLog
     */
    constructor() { 
        
        ScenarioRunContainerLog.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScenarioRunContainerLog</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScenarioRunContainerLog} obj Optional instance to populate.
     * @return {module:model/ScenarioRunContainerLog} The populated <code>ScenarioRunContainerLog</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScenarioRunContainerLog();

            if (data.hasOwnProperty('timeGenerated')) {
                obj['timeGenerated'] = ApiClient.convertToType(data['timeGenerated'], 'String');
            }
            if (data.hasOwnProperty('entrySource')) {
                obj['entrySource'] = ApiClient.convertToType(data['entrySource'], 'String');
            }
            if (data.hasOwnProperty('logEntry')) {
                obj['logEntry'] = ApiClient.convertToType(data['logEntry'], 'String');
            }
        }
        return obj;
    }


}

/**
 * date and time the record was created
 * @member {String} timeGenerated
 */
ScenarioRunContainerLog.prototype['timeGenerated'] = undefined;

/**
 * source of the log line. Possible values are stdout or stderr
 * @member {String} entrySource
 */
ScenarioRunContainerLog.prototype['entrySource'] = undefined;

/**
 * actual log line
 * @member {String} logEntry
 */
ScenarioRunContainerLog.prototype['logEntry'] = undefined;






export default ScenarioRunContainerLog;

