/**
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScenarioAnalysis from './ScenarioAnalysis';
import ScenarioAnalysisParameterValue from './ScenarioAnalysisParameterValue';
import ScenarioFailedAnalysisAllOf from './ScenarioFailedAnalysisAllOf';

/**
 * The ScenarioFailedAnalysis model module.
 * @module model/ScenarioFailedAnalysis
 * @version 0.0.1-SNAPSHOT
 */
class ScenarioFailedAnalysis {
    /**
     * Constructs a new <code>ScenarioFailedAnalysis</code>.
     * @alias module:model/ScenarioFailedAnalysis
     * @implements module:model/ScenarioAnalysis
     * @implements module:model/ScenarioFailedAnalysisAllOf
     * @param analysisId {String} the Simulator Analysis Id
     */
    constructor(analysisId) { 
        ScenarioAnalysis.initialize(this, analysisId);ScenarioFailedAnalysisAllOf.initialize(this);
        ScenarioFailedAnalysis.initialize(this, analysisId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, analysisId) { 
        obj['analysisId'] = analysisId;
    }

    /**
     * Constructs a <code>ScenarioFailedAnalysis</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScenarioFailedAnalysis} obj Optional instance to populate.
     * @return {module:model/ScenarioFailedAnalysis} The populated <code>ScenarioFailedAnalysis</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScenarioFailedAnalysis();
            ScenarioAnalysis.constructFromObject(data, obj);
            ScenarioFailedAnalysisAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('analysisId')) {
                obj['analysisId'] = ApiClient.convertToType(data['analysisId'], 'String');
            }
            if (data.hasOwnProperty('datasetList')) {
                obj['datasetList'] = ApiClient.convertToType(data['datasetList'], ['String']);
            }
            if (data.hasOwnProperty('parametersValues')) {
                obj['parametersValues'] = ApiClient.convertToType(data['parametersValues'], [ScenarioAnalysisParameterValue]);
            }
            if (data.hasOwnProperty('simulationId')) {
                obj['simulationId'] = ApiClient.convertToType(data['simulationId'], 'String');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
        }
        return obj;
    }


}

/**
 * the Simulator Analysis Id
 * @member {String} analysisId
 */
ScenarioFailedAnalysis.prototype['analysisId'] = undefined;

/**
 * the list of Dataset Id associated to this Scenario Analysis
 * @member {Array.<String>} datasetList
 */
ScenarioFailedAnalysis.prototype['datasetList'] = undefined;

/**
 * the list of Simulator Analysis parameters values
 * @member {Array.<module:model/ScenarioAnalysisParameterValue>} parametersValues
 */
ScenarioFailedAnalysis.prototype['parametersValues'] = undefined;

/**
 * the Simulation Run Id
 * @member {String} simulationId
 */
ScenarioFailedAnalysis.prototype['simulationId'] = undefined;

/**
 * the Simulation Run error message
 * @member {String} error
 */
ScenarioFailedAnalysis.prototype['error'] = undefined;


// Implement ScenarioAnalysis interface:
/**
 * the Simulator Analysis Id
 * @member {String} analysisId
 */
ScenarioAnalysis.prototype['analysisId'] = undefined;
/**
 * the list of Dataset Id associated to this Scenario Analysis
 * @member {Array.<String>} datasetList
 */
ScenarioAnalysis.prototype['datasetList'] = undefined;
/**
 * the list of Simulator Analysis parameters values
 * @member {Array.<module:model/ScenarioAnalysisParameterValue>} parametersValues
 */
ScenarioAnalysis.prototype['parametersValues'] = undefined;
// Implement ScenarioFailedAnalysisAllOf interface:
/**
 * the Simulation Run Id
 * @member {String} simulationId
 */
ScenarioFailedAnalysisAllOf.prototype['simulationId'] = undefined;
/**
 * the Simulation Run error message
 * @member {String} error
 */
ScenarioFailedAnalysisAllOf.prototype['error'] = undefined;




export default ScenarioFailedAnalysis;

