/**
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScenarioRunContainerLog from './ScenarioRunContainerLog';

/**
 * The ScenarioRunContainerLogs model module.
 * @module model/ScenarioRunContainerLogs
 * @version 0.0.1-SNAPSHOT
 */
class ScenarioRunContainerLogs {
    /**
     * Constructs a new <code>ScenarioRunContainerLogs</code>.
     * logs for a given container
     * @alias module:model/ScenarioRunContainerLogs
     */
    constructor() { 
        
        ScenarioRunContainerLogs.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScenarioRunContainerLogs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScenarioRunContainerLogs} obj Optional instance to populate.
     * @return {module:model/ScenarioRunContainerLogs} The populated <code>ScenarioRunContainerLogs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScenarioRunContainerLogs();

            if (data.hasOwnProperty('containerId')) {
                obj['containerId'] = ApiClient.convertToType(data['containerId'], 'String');
            }
            if (data.hasOwnProperty('computer')) {
                obj['computer'] = ApiClient.convertToType(data['computer'], 'String');
            }
            if (data.hasOwnProperty('logs')) {
                obj['logs'] = ApiClient.convertToType(data['logs'], [ScenarioRunContainerLog]);
            }
            if (data.hasOwnProperty('textLog')) {
                obj['textLog'] = ApiClient.convertToType(data['textLog'], 'String');
            }
        }
        return obj;
    }


}

/**
 * container ID for log source as seen by Docker engine
 * @member {String} containerId
 */
ScenarioRunContainerLogs.prototype['containerId'] = undefined;

/**
 * computer/node that's generating the log
 * @member {String} computer
 */
ScenarioRunContainerLogs.prototype['computer'] = undefined;

/**
 * the list of container logs in structured format
 * @member {Array.<module:model/ScenarioRunContainerLog>} logs
 */
ScenarioRunContainerLogs.prototype['logs'] = undefined;

/**
 * the plain text log if plainText option has been set
 * @member {String} textLog
 */
ScenarioRunContainerLogs.prototype['textLog'] = undefined;






export default ScenarioRunContainerLogs;

