/**
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ScenarioAllOf from './ScenarioAllOf';
import ScenarioAnalysis from './ScenarioAnalysis';
import ScenarioBase from './ScenarioBase';
import ScenarioFailedAnalysis from './ScenarioFailedAnalysis';
import ScenarioRunningAnalysis from './ScenarioRunningAnalysis';
import ScenarioSuccessfulAnalysis from './ScenarioSuccessfulAnalysis';
import ScenarioUser from './ScenarioUser';

/**
 * The Scenario model module.
 * @module model/Scenario
 * @version 0.0.1-SNAPSHOT
 */
class Scenario {
    /**
     * Constructs a new <code>Scenario</code>.
     * @alias module:model/Scenario
     * @implements module:model/ScenarioBase
     * @implements module:model/ScenarioAllOf
     * @param name {String} the Scenario name
     */
    constructor(name) { 
        ScenarioBase.initialize(this, name);ScenarioAllOf.initialize(this);
        Scenario.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Scenario</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Scenario} obj Optional instance to populate.
     * @return {module:model/Scenario} The populated <code>Scenario</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Scenario();
            ScenarioBase.constructFromObject(data, obj);
            ScenarioAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('parentId')) {
                obj['parentId'] = ApiClient.convertToType(data['parentId'], 'String');
            }
            if (data.hasOwnProperty('ownerId')) {
                obj['ownerId'] = ApiClient.convertToType(data['ownerId'], 'String');
            }
            if (data.hasOwnProperty('userList')) {
                obj['userList'] = ApiClient.convertToType(data['userList'], [ScenarioUser]);
            }
            if (data.hasOwnProperty('simulatorId')) {
                obj['simulatorId'] = ApiClient.convertToType(data['simulatorId'], 'String');
            }
            if (data.hasOwnProperty('analyses')) {
                obj['analyses'] = ApiClient.convertToType(data['analyses'], [ScenarioAnalysis]);
            }
            if (data.hasOwnProperty('successfulAnalyses')) {
                obj['successfulAnalyses'] = ApiClient.convertToType(data['successfulAnalyses'], [ScenarioSuccessfulAnalysis]);
            }
            if (data.hasOwnProperty('failedAnalyses')) {
                obj['failedAnalyses'] = ApiClient.convertToType(data['failedAnalyses'], [ScenarioFailedAnalysis]);
            }
            if (data.hasOwnProperty('runningAnalyses')) {
                obj['runningAnalyses'] = ApiClient.convertToType(data['runningAnalyses'], [ScenarioRunningAnalysis]);
            }
        }
        return obj;
    }


}

/**
 * the Scenario unique identifier
 * @member {String} id
 */
Scenario.prototype['id'] = undefined;

/**
 * the Scenario name
 * @member {String} name
 */
Scenario.prototype['name'] = undefined;

/**
 * the Scenario description
 * @member {String} description
 */
Scenario.prototype['description'] = undefined;

/**
 * the list of tags
 * @member {Array.<String>} tags
 */
Scenario.prototype['tags'] = undefined;

/**
 * the Scenario parent id
 * @member {String} parentId
 */
Scenario.prototype['parentId'] = undefined;

/**
 * the user id which own this Scenario
 * @member {String} ownerId
 */
Scenario.prototype['ownerId'] = undefined;

/**
 * the list of users Id with their role
 * @member {Array.<module:model/ScenarioUser>} userList
 */
Scenario.prototype['userList'] = undefined;

/**
 * the Simulator Id associated with this Scenario
 * @member {String} simulatorId
 */
Scenario.prototype['simulatorId'] = undefined;

/**
 * the configuration for next Analysis
 * @member {Array.<module:model/ScenarioAnalysis>} analyses
 */
Scenario.prototype['analyses'] = undefined;

/**
 * the configuration and information for last successful Analyses Runs
 * @member {Array.<module:model/ScenarioSuccessfulAnalysis>} successfulAnalyses
 */
Scenario.prototype['successfulAnalyses'] = undefined;

/**
 * the configuration and information for last failed Analyses Runs
 * @member {Array.<module:model/ScenarioFailedAnalysis>} failedAnalyses
 */
Scenario.prototype['failedAnalyses'] = undefined;

/**
 * the configuration and information for currently running Analyses Runs
 * @member {Array.<module:model/ScenarioRunningAnalysis>} runningAnalyses
 */
Scenario.prototype['runningAnalyses'] = undefined;


// Implement ScenarioBase interface:
/**
 * the Scenario unique identifier
 * @member {String} id
 */
ScenarioBase.prototype['id'] = undefined;
/**
 * the Scenario name
 * @member {String} name
 */
ScenarioBase.prototype['name'] = undefined;
/**
 * the Scenario description
 * @member {String} description
 */
ScenarioBase.prototype['description'] = undefined;
/**
 * the list of tags
 * @member {Array.<String>} tags
 */
ScenarioBase.prototype['tags'] = undefined;
/**
 * the Scenario parent id
 * @member {String} parentId
 */
ScenarioBase.prototype['parentId'] = undefined;
/**
 * the user id which own this Scenario
 * @member {String} ownerId
 */
ScenarioBase.prototype['ownerId'] = undefined;
/**
 * the list of users Id with their role
 * @member {Array.<module:model/ScenarioUser>} userList
 */
ScenarioBase.prototype['userList'] = undefined;
// Implement ScenarioAllOf interface:
/**
 * the Simulator Id associated with this Scenario
 * @member {String} simulatorId
 */
ScenarioAllOf.prototype['simulatorId'] = undefined;
/**
 * the configuration for next Analysis
 * @member {Array.<module:model/ScenarioAnalysis>} analyses
 */
ScenarioAllOf.prototype['analyses'] = undefined;
/**
 * the configuration and information for last successful Analyses Runs
 * @member {Array.<module:model/ScenarioSuccessfulAnalysis>} successfulAnalyses
 */
ScenarioAllOf.prototype['successfulAnalyses'] = undefined;
/**
 * the configuration and information for last failed Analyses Runs
 * @member {Array.<module:model/ScenarioFailedAnalysis>} failedAnalyses
 */
ScenarioAllOf.prototype['failedAnalyses'] = undefined;
/**
 * the configuration and information for currently running Analyses Runs
 * @member {Array.<module:model/ScenarioRunningAnalysis>} runningAnalyses
 */
ScenarioAllOf.prototype['runningAnalyses'] = undefined;




export default Scenario;

