/**
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SimulationAllOf from './SimulationAllOf';
import SimulationAnalysisParameterValue from './SimulationAnalysisParameterValue';
import SimulationBase from './SimulationBase';
import SimulationContainers from './SimulationContainers';

/**
 * The Simulation model module.
 * @module model/Simulation
 * @version 0.0.1-SNAPSHOT
 */
class Simulation {
    /**
     * Constructs a new <code>Simulation</code>.
     * @alias module:model/Simulation
     * @implements module:model/SimulationBase
     * @implements module:model/SimulationAllOf
     */
    constructor() { 
        SimulationBase.initialize(this);SimulationAllOf.initialize(this);
        Simulation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Simulation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Simulation} obj Optional instance to populate.
     * @return {module:model/Simulation} The populated <code>Simulation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Simulation();
            SimulationBase.constructFromObject(data, obj);
            SimulationAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('jobId')) {
                obj['jobId'] = ApiClient.convertToType(data['jobId'], 'String');
            }
            if (data.hasOwnProperty('ownerId')) {
                obj['ownerId'] = ApiClient.convertToType(data['ownerId'], 'String');
            }
            if (data.hasOwnProperty('workspaceId')) {
                obj['workspaceId'] = ApiClient.convertToType(data['workspaceId'], 'String');
            }
            if (data.hasOwnProperty('workspaceName')) {
                obj['workspaceName'] = ApiClient.convertToType(data['workspaceName'], 'String');
            }
            if (data.hasOwnProperty('scenarioId')) {
                obj['scenarioId'] = ApiClient.convertToType(data['scenarioId'], 'String');
            }
            if (data.hasOwnProperty('scenarioName')) {
                obj['scenarioName'] = ApiClient.convertToType(data['scenarioName'], 'String');
            }
            if (data.hasOwnProperty('simulatorId')) {
                obj['simulatorId'] = ApiClient.convertToType(data['simulatorId'], 'String');
            }
            if (data.hasOwnProperty('simulatorName')) {
                obj['simulatorName'] = ApiClient.convertToType(data['simulatorName'], 'String');
            }
            if (data.hasOwnProperty('simulatorVersion')) {
                obj['simulatorVersion'] = ApiClient.convertToType(data['simulatorVersion'], 'String');
            }
            if (data.hasOwnProperty('simulatorAnalysisId')) {
                obj['simulatorAnalysisId'] = ApiClient.convertToType(data['simulatorAnalysisId'], 'String');
            }
            if (data.hasOwnProperty('simulatorAnalysisName')) {
                obj['simulatorAnalysisName'] = ApiClient.convertToType(data['simulatorAnalysisName'], 'String');
            }
            if (data.hasOwnProperty('computeSize')) {
                obj['computeSize'] = ApiClient.convertToType(data['computeSize'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('startTime')) {
                obj['startTime'] = ApiClient.convertToType(data['startTime'], 'String');
            }
            if (data.hasOwnProperty('endTime')) {
                obj['endTime'] = ApiClient.convertToType(data['endTime'], 'String');
            }
            if (data.hasOwnProperty('datasetList')) {
                obj['datasetList'] = ApiClient.convertToType(data['datasetList'], ['String']);
            }
            if (data.hasOwnProperty('parametersValues')) {
                obj['parametersValues'] = ApiClient.convertToType(data['parametersValues'], [SimulationAnalysisParameterValue]);
            }
            if (data.hasOwnProperty('sendInputToDataWarehouse')) {
                obj['sendInputToDataWarehouse'] = ApiClient.convertToType(data['sendInputToDataWarehouse'], 'Boolean');
            }
            if (data.hasOwnProperty('dataWarehouseDB')) {
                obj['dataWarehouseDB'] = ApiClient.convertToType(data['dataWarehouseDB'], 'String');
            }
            if (data.hasOwnProperty('resultsEventBusResourceUri')) {
                obj['resultsEventBusResourceUri'] = ApiClient.convertToType(data['resultsEventBusResourceUri'], 'String');
            }
            if (data.hasOwnProperty('simulationEventBusResourceUri')) {
                obj['simulationEventBusResourceUri'] = ApiClient.convertToType(data['simulationEventBusResourceUri'], 'String');
            }
            if (data.hasOwnProperty('nodeLabel')) {
                obj['nodeLabel'] = ApiClient.convertToType(data['nodeLabel'], 'String');
            }
            if (data.hasOwnProperty('initContainers')) {
                obj['initContainers'] = ApiClient.convertToType(data['initContainers'], [SimulationContainers]);
            }
            if (data.hasOwnProperty('mainContainer')) {
                obj['mainContainer'] = SimulationContainers.constructFromObject(data['mainContainer']);
            }
        }
        return obj;
    }


}

/**
 * the Simulation
 * @member {String} id
 */
Simulation.prototype['id'] = undefined;

/**
 * the Platform compute cluster Job Id
 * @member {String} jobId
 */
Simulation.prototype['jobId'] = undefined;

/**
 * the user id which own this simulation
 * @member {String} ownerId
 */
Simulation.prototype['ownerId'] = undefined;

/**
 * the Workspace Id
 * @member {String} workspaceId
 */
Simulation.prototype['workspaceId'] = undefined;

/**
 * the Workspace name
 * @member {String} workspaceName
 */
Simulation.prototype['workspaceName'] = undefined;

/**
 * the Scenario Id
 * @member {String} scenarioId
 */
Simulation.prototype['scenarioId'] = undefined;

/**
 * the Scenario name
 * @member {String} scenarioName
 */
Simulation.prototype['scenarioName'] = undefined;

/**
 * the Simulator Id
 * @member {String} simulatorId
 */
Simulation.prototype['simulatorId'] = undefined;

/**
 * the Simulator name
 * @member {String} simulatorName
 */
Simulation.prototype['simulatorName'] = undefined;

/**
 * the Simulator version
 * @member {String} simulatorVersion
 */
Simulation.prototype['simulatorVersion'] = undefined;

/**
 * the Simulator Analysis id
 * @member {String} simulatorAnalysisId
 */
Simulation.prototype['simulatorAnalysisId'] = undefined;

/**
 * the Simulator Analysis name
 * @member {String} simulatorAnalysisName
 */
Simulation.prototype['simulatorAnalysisName'] = undefined;

/**
 * the compute size needed for this Analysis. Standard sizes are basic and highcpu. Default is basic
 * @member {String} computeSize
 */
Simulation.prototype['computeSize'] = undefined;

/**
 * the Simulation state
 * @member {String} state
 */
Simulation.prototype['state'] = undefined;

/**
 * the Simulation start Date Time
 * @member {String} startTime
 */
Simulation.prototype['startTime'] = undefined;

/**
 * the Simulation end Date Time
 * @member {String} endTime
 */
Simulation.prototype['endTime'] = undefined;

/**
 * the list of Dataset Id associated to this Analysis
 * @member {Array.<String>} datasetList
 */
Simulation.prototype['datasetList'] = undefined;

/**
 * the list of Simulator Analysis parameters values
 * @member {Array.<module:model/SimulationAnalysisParameterValue>} parametersValues
 */
Simulation.prototype['parametersValues'] = undefined;

/**
 * whether or not the Dataset values and the input parameters values are send to the DataWarehouse prior to Simulation Run
 * @member {Boolean} sendInputToDataWarehouse
 */
Simulation.prototype['sendInputToDataWarehouse'] = undefined;

/**
 * the DataWarehouse database name to send data if sendInputToDataWarehouse is set
 * @member {String} dataWarehouseDB
 */
Simulation.prototype['dataWarehouseDB'] = undefined;

/**
 * the event bus which receive Workspace Simulation results messages. Message won't be send if this is not set
 * @member {String} resultsEventBusResourceUri
 */
Simulation.prototype['resultsEventBusResourceUri'] = undefined;

/**
 * the event bus which receive Workspace Simulation events messages. Message won't be send if this is not set
 * @member {String} simulationEventBusResourceUri
 */
Simulation.prototype['simulationEventBusResourceUri'] = undefined;

/**
 * the node label request
 * @member {String} nodeLabel
 */
Simulation.prototype['nodeLabel'] = undefined;

/**
 * the list of init containers
 * @member {Array.<module:model/SimulationContainers>} initContainers
 */
Simulation.prototype['initContainers'] = undefined;

/**
 * @member {module:model/SimulationContainers} mainContainer
 */
Simulation.prototype['mainContainer'] = undefined;


// Implement SimulationBase interface:
/**
 * the Simulation
 * @member {String} id
 */
SimulationBase.prototype['id'] = undefined;
/**
 * the Platform compute cluster Job Id
 * @member {String} jobId
 */
SimulationBase.prototype['jobId'] = undefined;
/**
 * the user id which own this simulation
 * @member {String} ownerId
 */
SimulationBase.prototype['ownerId'] = undefined;
/**
 * the Workspace Id
 * @member {String} workspaceId
 */
SimulationBase.prototype['workspaceId'] = undefined;
/**
 * the Workspace name
 * @member {String} workspaceName
 */
SimulationBase.prototype['workspaceName'] = undefined;
/**
 * the Scenario Id
 * @member {String} scenarioId
 */
SimulationBase.prototype['scenarioId'] = undefined;
/**
 * the Scenario name
 * @member {String} scenarioName
 */
SimulationBase.prototype['scenarioName'] = undefined;
/**
 * the Simulator Id
 * @member {String} simulatorId
 */
SimulationBase.prototype['simulatorId'] = undefined;
/**
 * the Simulator name
 * @member {String} simulatorName
 */
SimulationBase.prototype['simulatorName'] = undefined;
/**
 * the Simulator version
 * @member {String} simulatorVersion
 */
SimulationBase.prototype['simulatorVersion'] = undefined;
/**
 * the Simulator Analysis id
 * @member {String} simulatorAnalysisId
 */
SimulationBase.prototype['simulatorAnalysisId'] = undefined;
/**
 * the Simulator Analysis name
 * @member {String} simulatorAnalysisName
 */
SimulationBase.prototype['simulatorAnalysisName'] = undefined;
/**
 * the compute size needed for this Analysis. Standard sizes are basic and highcpu. Default is basic
 * @member {String} computeSize
 */
SimulationBase.prototype['computeSize'] = undefined;
/**
 * the Simulation state
 * @member {String} state
 */
SimulationBase.prototype['state'] = undefined;
/**
 * the Simulation start Date Time
 * @member {String} startTime
 */
SimulationBase.prototype['startTime'] = undefined;
/**
 * the Simulation end Date Time
 * @member {String} endTime
 */
SimulationBase.prototype['endTime'] = undefined;
// Implement SimulationAllOf interface:
/**
 * the list of Dataset Id associated to this Analysis
 * @member {Array.<String>} datasetList
 */
SimulationAllOf.prototype['datasetList'] = undefined;
/**
 * the list of Simulator Analysis parameters values
 * @member {Array.<module:model/SimulationAnalysisParameterValue>} parametersValues
 */
SimulationAllOf.prototype['parametersValues'] = undefined;
/**
 * whether or not the Dataset values and the input parameters values are send to the DataWarehouse prior to Simulation Run
 * @member {Boolean} sendInputToDataWarehouse
 */
SimulationAllOf.prototype['sendInputToDataWarehouse'] = undefined;
/**
 * the DataWarehouse database name to send data if sendInputToDataWarehouse is set
 * @member {String} dataWarehouseDB
 */
SimulationAllOf.prototype['dataWarehouseDB'] = undefined;
/**
 * the event bus which receive Workspace Simulation results messages. Message won't be send if this is not set
 * @member {String} resultsEventBusResourceUri
 */
SimulationAllOf.prototype['resultsEventBusResourceUri'] = undefined;
/**
 * the event bus which receive Workspace Simulation events messages. Message won't be send if this is not set
 * @member {String} simulationEventBusResourceUri
 */
SimulationAllOf.prototype['simulationEventBusResourceUri'] = undefined;
/**
 * the node label request
 * @member {String} nodeLabel
 */
SimulationAllOf.prototype['nodeLabel'] = undefined;
/**
 * the list of init containers
 * @member {Array.<module:model/SimulationContainers>} initContainers
 */
SimulationAllOf.prototype['initContainers'] = undefined;
/**
 * @member {module:model/SimulationContainers} mainContainer
 */
SimulationAllOf.prototype['mainContainer'] = undefined;




export default Simulation;

