/**
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The User model module.
 * @module model/User
 * @version 0.0.1-SNAPSHOT
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * a User
     * @alias module:model/User
     * @param name {String} the User name
     * @param platformRoles {Array.<module:model/User.PlatformRolesEnum>} the list of Platform roles
     */
    constructor(name, platformRoles) { 
        
        User.initialize(this, name, platformRoles);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, platformRoles) { 
        obj['name'] = name;
        obj['platformRoles'] = platformRoles;
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('platformRoles')) {
                obj['platformRoles'] = ApiClient.convertToType(data['platformRoles'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * the User unique identifier
 * @member {String} id
 */
User.prototype['id'] = undefined;

/**
 * the User name
 * @member {String} name
 */
User.prototype['name'] = undefined;

/**
 * the list of Platform roles
 * @member {Array.<module:model/User.PlatformRolesEnum>} platformRoles
 */
User.prototype['platformRoles'] = undefined;





/**
 * Allowed values for the <code>platformRoles</code> property.
 * @enum {String}
 * @readonly
 */
User['PlatformRolesEnum'] = {

    /**
     * value: "Admin"
     * @const
     */
    "Admin": "Admin",

    /**
     * value: "User"
     * @const
     */
    "User": "User",

    /**
     * value: "ConnectorDeveloper"
     * @const
     */
    "ConnectorDeveloper": "ConnectorDeveloper"
};



export default User;

