/**
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CosmotechApi);
  }
}(this, function(expect, CosmotechApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CosmotechApi.ScenarioSuccessfulAnalysis();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ScenarioSuccessfulAnalysis', function() {
    it('should create an instance of ScenarioSuccessfulAnalysis', function() {
      // uncomment below and update the code to test ScenarioSuccessfulAnalysis
      //var instane = new CosmotechApi.ScenarioSuccessfulAnalysis();
      //expect(instance).to.be.a(CosmotechApi.ScenarioSuccessfulAnalysis);
    });

    it('should have the property analysisId (base name: "analysisId")', function() {
      // uncomment below and update the code to test the property analysisId
      //var instance = new CosmotechApi.ScenarioSuccessfulAnalysis();
      //expect(instance).to.be();
    });

    it('should have the property datasetList (base name: "datasetList")', function() {
      // uncomment below and update the code to test the property datasetList
      //var instance = new CosmotechApi.ScenarioSuccessfulAnalysis();
      //expect(instance).to.be();
    });

    it('should have the property parametersValues (base name: "parametersValues")', function() {
      // uncomment below and update the code to test the property parametersValues
      //var instance = new CosmotechApi.ScenarioSuccessfulAnalysis();
      //expect(instance).to.be();
    });

    it('should have the property simulationId (base name: "simulationId")', function() {
      // uncomment below and update the code to test the property simulationId
      //var instance = new CosmotechApi.ScenarioSuccessfulAnalysis();
      //expect(instance).to.be();
    });

  });

}));
