/**
 * Cosmo Tech Plaform API
 * Cosmo Tech Platform API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CosmotechApi);
  }
}(this, function(expect, CosmotechApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CosmotechApi.ScenarioRunStartContainers();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ScenarioRunStartContainers', function() {
    it('should create an instance of ScenarioRunStartContainers', function() {
      // uncomment below and update the code to test ScenarioRunStartContainers
      //var instane = new CosmotechApi.ScenarioRunStartContainers();
      //expect(instance).to.be.a(CosmotechApi.ScenarioRunStartContainers);
    });

    it('should have the property nodeLabel (base name: "nodeLabel")', function() {
      // uncomment below and update the code to test the property nodeLabel
      //var instance = new CosmotechApi.ScenarioRunStartContainers();
      //expect(instance).to.be();
    });

    it('should have the property fetchDatasetContainers (base name: "fetchDatasetContainers")', function() {
      // uncomment below and update the code to test the property fetchDatasetContainers
      //var instance = new CosmotechApi.ScenarioRunStartContainers();
      //expect(instance).to.be();
    });

    it('should have the property fetchScenarioParametersContainer (base name: "fetchScenarioParametersContainer")', function() {
      // uncomment below and update the code to test the property fetchScenarioParametersContainer
      //var instance = new CosmotechApi.ScenarioRunStartContainers();
      //expect(instance).to.be();
    });

    it('should have the property applyParametersContainer (base name: "applyParametersContainer")', function() {
      // uncomment below and update the code to test the property applyParametersContainer
      //var instance = new CosmotechApi.ScenarioRunStartContainers();
      //expect(instance).to.be();
    });

    it('should have the property validateDataContainer (base name: "validateDataContainer")', function() {
      // uncomment below and update the code to test the property validateDataContainer
      //var instance = new CosmotechApi.ScenarioRunStartContainers();
      //expect(instance).to.be();
    });

    it('should have the property sendDataWarehouseContainer (base name: "sendDataWarehouseContainer")', function() {
      // uncomment below and update the code to test the property sendDataWarehouseContainer
      //var instance = new CosmotechApi.ScenarioRunStartContainers();
      //expect(instance).to.be();
    });

    it('should have the property preRunContainer (base name: "preRunContainer")', function() {
      // uncomment below and update the code to test the property preRunContainer
      //var instance = new CosmotechApi.ScenarioRunStartContainers();
      //expect(instance).to.be();
    });

    it('should have the property runContainer (base name: "runContainer")', function() {
      // uncomment below and update the code to test the property runContainer
      //var instance = new CosmotechApi.ScenarioRunStartContainers();
      //expect(instance).to.be();
    });

    it('should have the property postRunContainer (base name: "postRunContainer")', function() {
      // uncomment below and update the code to test the property postRunContainer
      //var instance = new CosmotechApi.ScenarioRunStartContainers();
      //expect(instance).to.be();
    });

  });

}));
